### ISSUE TITLE
Figure out Twilio XML format

### ISSUE THREAD

**Issue by dfaulken** [umts/garrulous-garbanzo#3]
To reach MVP status, the next thing to do would be making the Twilio XML get request work properly, with the MVC code required to do that. Then we can make the calendar.

**Comment by phantompatrol** [comment]
Bah, says me:

https://github.com/twilio/twilio-ruby

**Comment by phantompatrol** [comment]
Or you could make a tiny xml app, and use that: https://www.twilio.com/labs/twimlets

**Comment by werebus** [comment]
Twilio Ruby is, in my mind, almost overkill if you're not making outgoing API requests.  All you really need is a view something like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial timeout="10"><%= @current_on_call_number %></Dial>
</Response>
```

to just forward phone calls. Text messages are only a little bit more complicated.

Twimlets are secretly just php scripts where Twilio is doing the hosting for you.

**Comment by phantompatrol** [comment]
Correction: Twimlets are not 'xml apps'. I had XML on the brain. Yes totally, I was just hanging on the 'not hosted by us' part. Further, we need number to be dynamically chosen by the schedule. Got 'cha.

**Comment by dfaulken** [comment]
Ref: https://www.twilio.com/docs/api/twiml/dial

**Comment by dfaulken** [comment]
Maybe it'd be worth having calls and texts come from a number that we can save in our contacts, so that we know that incoming calls/texts are for on-call reasons?

**Comment by dfaulken** [comment]
https://github.com/umts/garrulous-garbanzo/commit/1edae8ae0410ca805cb530b2fc970a571ea3acad

**Comment by dfaulken** [comment]
I exposed my dev environment using ngrok, set up a Twilio trial account, and made a test call and SMS which were forwarded correctly. :smile:
